# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c54a924cdfa1cc921454d609e3830e8fcbd1151f5c58e24049ec80f6ca14ec6316243054929779c9e4cb4c690f4320098ffa12d679a020df5281b85c6da38c8

test:
  secret_key_base: ce97a9e5c86ee8abf0e0a3ebac912fe29044fdc79c54b49d51b7cdb241a3d5aa636399c4d84740e6c6b08a308a6863cb4ab0d291fb6d8d64be31fa56234da0b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
